version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=webhook_catcher
      - POSTGRES_USER=webhook_user
      - POSTGRES_PASSWORD=webhook_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - admin_network
    restart: unless-stopped

  backend:
    container_name: zap-webhook-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - admin_network

  frontend:
    container_name: zap-webhook-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3420:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    networks:
      - admin_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  admin_network:
    external: true
